Repository parodos-dev/parodos, pull requests merged in 2023-08, with the labels that each got.

#488 fix boolean type column
  integration-tests/src/test/java/com/redhat/parodos/flows/SimpleRestartWorkFlowTest.java
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
  workflow-service/src/main/resources/db/changelog/tables.xml
Labels: lgtm, approved

#494 FLPATH-544: `prebuilt-tasks` module must NOT depend on `workflow-service-sdk`
  prebuilt-tasks/pom.xml
Labels: lgtm, approved, jira/valid-reference

#496 Fix unit test for PlanStatusWorkFlowChecker
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/vmmigration/checker/PlanStatusWorkFlowCheckerTest.java
Labels: lgtm, approved

#503 Temporarily disable security-checks
  .github/workflows/test.yml
Labels: approved

#470 separate workflow-examples from workflow-service
  .github/workflows/test.yml
  Makefile
  docker-compose/docker-compose.yml
  hack/manifests/testing/kustomization.yaml
  integration-tests/Dockerfile
  workflow-service/Dockerfile
Labels: lgtm, approved

#505 FLPATH-556:return pending requests
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/project/controller/ProjectAccessController.java
  workflow-service/src/main/java/com/redhat/parodos/project/dto/response/ProjectAccessRequestDTO.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectAccessService.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectAccessServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/project/controller/ProjectAccessControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/project/service/ProjectAccessServiceImplTest.java
Labels: lgtm, approved, jira/valid-reference

#499 Fix submit analysis task
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/migrationtoolkit/SubmitAnalysisTaskTest.java
Labels: lgtm, approved
