Repository parodos-dev/parodos, pull requests merged in 2023-05, with the labels that each got.

#293 Use the WorkFlowStatus instance instead of name()
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/enums/WorkFlowStatus.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptor.java
Labels: lgtm, approved

#296 simpler status usage
  workflow-engine/src/main/java/com/redhat/parodos/workflows/work/WorkReportPredicate.java
  workflow-engine/src/main/java/com/redhat/parodos/workflows/workflow/ParallelFlowReport.java
  workflow-engine/src/main/java/com/redhat/parodos/workflows/workflow/SequentialFlow.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/CheckerWorkFlowPostInterceptor.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptorTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
Labels: lgtm, approved

#299 Unify the setting/getting of project-id from context
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/BaseWorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/utils/WorkContextUtils.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/utils/WorkContextUtilsTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTask.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTaskTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepositoryTest.java
Labels: lgtm, approved

#292 kubeapi workflow examples with SDK
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/KubeapiWorkFlow.java
Labels: lgtm, approved

#298 Change user ID type in response to UUID
  workflow-service/src/main/java/com/redhat/parodos/user/dto/UserResponseDTO.java
  workflow-service/src/test/java/com/redhat/parodos/user/service/UserServiceImplTest.java
Labels: lgtm, approved

#294 FLPATH-313: get workflow by projectId
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/ComplexWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/EscalationFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/KubeapiWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/PrebuiltWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/SimpleWorkFlow.java
  workflow-service-sdk/README.md
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/GetStatusByProjectId200Response.md
  workflow-service-sdk/docs/WorkFlowResponseDTO.md
  workflow-service-sdk/docs/WorkflowApi.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/WorkflowApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/invoker/JSON.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/GetStatusByProjectId200Response.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowResponseDTO.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/WorkflowApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/ProjectResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowContextResponseDTOTest.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/project/repository/ProjectRepository.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectService.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityUtils.java
  workflow-service/src/main/java/com/redhat/parodos/user/entity/User.java
  workflow-service/src/main/java/com/redhat/parodos/user/service/UserService.java
  workflow-service/src/main/java/com/redhat/parodos/user/service/UserServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/main/resources/db/changelog/data.xml
  workflow-service/src/main/resources/db/changelog/tables.xml
  workflow-service/src/test/java/com/redhat/parodos/project/repository/ProjectRepositoryTest.java
  workflow-service/src/test/java/com/redhat/parodos/project/service/ProjectServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/repository/RepositoryTestBase.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceDataTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/controller/WorkFlowControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm, approved, jira/valid-reference

#305 NO-ISSUE: Version bump
  Makefile
  coverage/pom.xml
  notification-service-sdk/README.md
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiClient.java
  notification-service/README.md
  notification-service/licenses/THIRD-PARTY.txt
  pom.xml
  workflow-service-sdk/README.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/invoker/ApiClient.java
  workflow-service/src/main/resources/application.yml
Labels: lgtm, approved, jira/valid-reference

#307 Use static imports in tests
  notification-service/src/test/java/com/redhat/parodos/notification/dto/NotificationRecordResponseDTOTest.java
  notification-service/src/test/java/com/redhat/parodos/notification/service/NotificationMessageServiceTest.java
  notification-service/src/test/java/com/redhat/parodos/notification/service/NotificationRecordServiceTests.java
  pattern-detection-library/src/test/java/com/redhat/parodos/patterndetection/PatternDetectorTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/jira/JiraTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/kubeapi/KubeapiWorkFlowTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/notification/NotificationWorkFlowTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTaskTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/engine/WorkFlowEngineImplTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/ConditionalFlowTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/ParallelFlowExecutorTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/ParallelFlowReportTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/ParallelFlowTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/RepeatFlowTest.java
  workflow-engine/src/test/java/com/redhat/parodos/workflows/workflow/SequentialFlowTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/base/BaseInfrastructureWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/complex/checker/NamespaceApprovalWorkFlowCheckerTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/complex/task/OnboardingAssessmentTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/escalation/JiraTicketApprovalEscalationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/AppLinkEmailNotificationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketEmailNotificationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/NotificationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/SecureAPIGetTestTaskTest.java
  workflow-service/src/test/java/com/redhat/parodos/project/controller/ProjectControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/project/service/ProjectServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/user/service/UserServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/parameter/WorkParameterServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptorTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowPropertiesAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/controller/WorkFlowControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegateTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImplTest.java
Labels: lgtm, approved

#308 Avoid static import in production code
  notification-service/src/main/java/com/redhat/parodos/notification/security/SecurityConfiguration.java
  notification-service/src/main/java/com/redhat/parodos/notification/util/SearchUtil.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Assessment.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Checker.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Escalation.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Infrastructure.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Parameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/WorkFlowProperties.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jira/JiraTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/escalation/JiraTicketApprovalEscalationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/AppLinkEmailNotificationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketEmailNotificationWorkFlowTask.java
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityConfiguration.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/ContinuedWorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/MainWorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/ControllerMockClient.java
Labels: lgtm, approved

#309 Move "NotificationRecord" into "integration-tests" module
  integration-tests/pom.xml
  integration-tests/src/test/java/com/redhat/parodos/integration/notification/NotificationRecord.java
  workflow-examples/pom.xml
Labels: lgtm, approved

#310 Code clean-ups
  parodos-model-api/pom.xml
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTypeTest.java
Labels: lgtm, approved

#313 Update utils classes according to convention
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/utils/CredUtils.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/utils/WorkContextUtils.java
  sdk-utils/src/main/java/com/redhat/parodos/sdkutils/SdkUtils.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityUtils.java
Labels: lgtm, approved

#314 Change JsonInclude.NON_EMPTY to NON_NULL
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowContextResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowOptionsResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowStatusResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkStatusResponseDTO.java
Labels: lgtm, approved

#319 Add a badge with push workflow status
  README.md
Labels: lgtm, approved

#318 Exclude notification-service-sdk from coverage
  coverage/pom.xml
Labels: lgtm, approved

#322 Fix: change check function for waitProjectAsync
  sdk-utils/src/main/java/com/redhat/parodos/sdkutils/SdkUtils.java
Labels: lgtm, approved

#300 Feat: add git prebuilt-tasks
  prebuilt-tasks/pom.xml
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/git/GitArchiveTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/git/GitCloneTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/git/GitUtils.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/git/GitArchiveTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/git/GitCloneTaskTest.java
Labels: lgtm, approved

#328 Revert "Fix: change check function for waitProjectAsync"
  sdk-utils/src/main/java/com/redhat/parodos/sdkutils/SdkUtils.java
Labels: lgtm, approved

#327 Fix typo in pull_request_template.md
  .github/pull_request_template.md
Labels: lgtm, approved

#329 Fail correctly when execution fails
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/controller/WorkFlowControllerTest.java
Labels: lgtm, approved

#333 NO-ISSUE: Fix tibco link
  external-dependencies/download-tibco.sh
Labels: lgtm, approved, jira/valid-reference

#343 Add non-empty validation for users
  workflow-service/src/main/java/com/redhat/parodos/project/controller/ProjectController.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/project/controller/ProjectControllerTest.java
Labels: lgtm, approved

#339 FLPATH-394 - Speedup integration test execution
  sdk-utils/src/main/java/com/redhat/parodos/sdkutils/SdkUtils.java
Labels: lgtm, approved

#348 Fix local run of integration tests
  workflow-service/start_workflow_service.sh
Labels: lgtm, approved

#349 Create Makefile target `deploy-to-kind`
  Makefile
Labels: lgtm, approved

#350 Update exception to concrete type
  workflow-service/src/main/java/com/redhat/parodos/user/service/UserServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/user/service/UserServiceImplTest.java
Labels: lgtm, approved

#351 Refactor ResourceNotFoundException
  workflow-service/src/main/java/com/redhat/parodos/common/exceptions/ResourceNotFoundException.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/user/service/UserServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
Labels: lgtm, approved

#352 Add IllegalWorkFlowStateException
  workflow-service/src/main/java/com/redhat/parodos/common/controller/ControllerExceptionHandler.java
  workflow-service/src/main/java/com/redhat/parodos/common/exceptions/IllegalWorkFlowStateException.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
Labels: lgtm, approved

#353 FLPATH-390: vm demo api
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/OcpOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/VmOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/checker/AnsibleCompletionWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/checker/IpAddressProvisioningWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/AapGetJobResponseArtifacts.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/AapGetJobResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/GetRequestItemResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/OrderServiceCatalogItemRequestDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/OrderServiceCatalogItemRequestVariable.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/OrderServiceCatalogItemResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/OrderServiceCatalogItemResponseResult.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/NotificationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/OnboardingVmAssessmentTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/ServiceNowTicketCreationWorkFlowTask.java
Labels: do-not-merge/work-in-progress, do-not-merge/hold, jira/valid-reference

#355 Vm onboarding demo api
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/VmOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/AapGetJobResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/AapJobLaunchRequestDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/ServiceNowRequestDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/ServiceNowResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/ServiceNowResponseResult.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/AapLaunchJobWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/ServiceNowTicketCreationWorkFlowTask.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegate.java
Labels: do-not-merge/work-in-progress, do-not-merge/hold

#356 Vm onboarding demo api
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/VmOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/checker/IncidentWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/checker/IpAddressProvisioningWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/dto/AapJobLaunchRequestDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/AapLaunchJobWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/NotificationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/vmonboarding/task/ServiceNowTicketCreationWorkFlowTask.java
Labels: do-not-merge/hold

#341 Add a workflow task that uses REST
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/rest/RestService.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/rest/RestServiceImpl.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/rest/RestWorkFlowTask.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/rest/RestWorkFlowTaskTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/RestWorkFlowConfiguration.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/rest/RestWorkFlow.java
Labels: lgtm, approved

#335 fix: check workflow exists when executing
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
Labels: lgtm, approved

#359 Remove unneeded class variable
  sdk-utils/src/main/java/com/redhat/parodos/sdkutils/SdkUtils.java
Labels: lgtm, approved

#360 notification-service: cleanup code
  notification-service/src/main/java/com/redhat/parodos/notification/config/ModelMapperConfig.java
  notification-service/src/main/java/com/redhat/parodos/notification/jpa/entity/NotificationGroup.java
  notification-service/src/main/java/com/redhat/parodos/notification/jpa/entity/NotificationMessage.java
  notification-service/src/main/java/com/redhat/parodos/notification/jpa/entity/NotificationUser.java
Labels: lgtm, approved

#358 Integration test: make workflow a bit faster
  .github/workflows/test.yml
Labels: lgtm, approved

#361 Extract shared code in integration-tests
  integration-tests/src/test/java/com/redhat/parodos/flows/ComplexWorkFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/EscalationFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/PrebuiltWorkFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/SimpleRollbackWorkFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/SimpleWorkFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/base/BaseIntegrationTest.java
Labels: lgtm, approved

#363 Remove unused variable
  notification-service/src/main/java/com/redhat/parodos/notification/controller/advice/ControllerExceptionHandler.java
Labels: lgtm, approved

#362 Enable checkstyle for integration-tests
  integration-tests/pom.xml
  integration-tests/src/test/java/com/redhat/parodos/integration/notification/NotificationRecordTest.java
Labels: lgtm, approved

#367 Add missing annotations
  workflow-engine/src/main/java/com/redhat/parodos/workflows/work/WorkContext.java
  workflow-service/src/main/java/com/redhat/parodos/project/entity/ProjectUserRole.java
Labels: lgtm, approved

#366 Update integration tests to match coding conventions
  integration-tests/src/test/java/com/redhat/parodos/flows/SimpleWorkFlowTest.java
  integration-tests/src/test/java/com/redhat/parodos/flows/common/WorkFlowTestBuilder.java
Labels: lgtm, approved

#369 Add DefaultWorkFlowPostInterceptor
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/DefaultWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptor.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/DefaultWorkFlowPostInterceptorTest.java
Labels: lgtm, approved

#372 Add banner to the notification service
  notification-service/src/main/resources/application.yml
  notification-service/src/main/resources/banner.txt
Labels: lgtm, approved

#373 Refactor async execution methods
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/CheckerWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowExecutor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowExecutorImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptorTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowExecutorImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm, approved

#374 Refactor rollback execution
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowExecutorImpl.java
Labels: lgtm, approved

#381 Fix wrong package name in import statement
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/WorkFlowTaskExecutionLog.java
Labels: lgtm, approved

#384 Replace powermock.mock with mockito.mock
  workflow-examples/pom.xml
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubePlanTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubeRetrieveTest.java
Labels: lgtm, approved

#385 Workflow examples cleanup
  Makefile
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubeBaseTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubePlanTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubeRetrieveTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubeTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/move2kube/task/Move2KubeTransformTest.java
Labels: lgtm, approved

#382 feat: add initial move2kube manifests
  hack/manifests/move2kube/kustomization.yaml
  hack/manifests/move2kube/move2kube-deployment.yaml
  hack/manifests/move2kube/namespace.yaml
Labels: lgtm, approved

#388 Add rule to verify static imports of Mockito
  checkstyle.xml
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/migrationtoolkit/CreateApplicationTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/migrationtoolkit/GetAnalysisTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/migrationtoolkit/GetApplicationTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/migrationtoolkit/SubmitAnalysisTaskTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/rest/RestWorkFlowTaskTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowExecutorImplTest.java
Labels: lgtm, approved

#390 FLPATH-377: fix log not found
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowLogServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowLogServiceImplTest.java
Labels: lgtm, approved, jira/valid-reference

#379 Add a workflow task that uses JDBC
  prebuilt-tasks/pom.xml
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jdbc/JdbcService.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jdbc/JdbcServiceImpl.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jdbc/JdbcWorkFlowTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jdbc/README.md
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/jdbc/JdbcWorkFlowTaskTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/JdbcWorkFlowConfiguration.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/jdbc/JdbcWorkFlow.java
Labels: lgtm, approved
