Repository parodos-dev/parodos, pull requests merged in 2023-04, with the labels that each got.

#195 Add Parodos banner
  workflow-service/src/main/resources/application.yml
  workflow-service/src/main/resources/banner.txt
Labels: lgtm, approved

#196 notification-service: Enable h2 console in local configuration
  notification-service/src/main/resources/application-local.yml
Labels: lgtm, approved

#201 feat: add test user on notification-service
  notification-service/src/main/resources/db/data/user.csv
  notification-service/src/main/resources/test-server.ldif
Labels: lgtm, approved

#198 Import cleanup
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterTypeTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/AdGroupsWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/LoadBalancerWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/NamespaceWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SingleSignOnWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SplunkMonitoringWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SslCertificationWorkFlowTask.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/CustomWorkFlowConfiguration.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/task/CustomWorkFlowTask.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/master/task/OnboardingAssessmentTaskTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/WorkFlowDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/converter/WorkFlowParametersConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/converter/WorkFlowTaskDefinitionDTOConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkStatusResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegate.java
  workflow-service/src/test/java/com/redhat/parodos/project/controller/ProjectControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/WorkFlowDelegateTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImplTest.java
Labels: lgtm, approved

#130 Introduce Jira Tasks
  pom.xml
  prebuilt-tasks/pom.xml
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jira/JiraIssue.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jira/JiraTask.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/jira/JiraTaskTest.java
  workflow-engine/pom.xml
Labels: lgtm, approved

#194 Refactor workflow aspect
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/CheckerWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/ContinuedWorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/InitialMasterWorkflowInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/MasterWorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionFactory.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowPostInterceptor.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionFactoryTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptorTest.java
Labels: lgtm, approved

#207 Update Jira java-client version
  prebuilt-tasks/pom.xml
Labels: lgtm, approved

#208 pom.xml: use dependecy management
  notification-service-sdk/pom.xml
  notification-service/pom.xml
  parodos-model-api/pom.xml
  pom.xml
  prebuilt-tasks/pom.xml
  workflow-engine/pom.xml
  workflow-examples/pom.xml
  workflow-service-sdk/pom.xml
  workflow-service/pom.xml
Labels: lgtm, approved

#189 FLPATH-250 & FLPATH-251: create jira ticket
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/enums/WorkFlowStatus.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/BaseWorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/enums/WorkFlowTaskStatus.java
  workflow-engine/src/main/java/com/redhat/parodos/workflows/work/WorkStatus.java
  workflow-examples/pom.xml
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/OcpOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/checker/JiraTicketApprovalWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/CreateJiraTicketRequestDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/CreateJiraTicketResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/GetJiraTicketResponseDto.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/GetJiraTicketResponseValue.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/JiraApprovalStatus.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/JiraStatus.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/dto/RequestFieldValues.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/OcpAppDeploymentWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/custom/CustomWorkFlowConfiguration.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/custom/task/CustomWorkFlowTask.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/custom/task/SimpleWorkFlowCheckerTask.java
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkFlowCheckerTaskRequestDTO.md
  workflow-service-sdk/docs/WorkFlowResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowCheckerTaskRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowResponseDTO.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImplTest.java
Labels: approved, jira/valid-reference

#213 Add steps to create and configure local PostgreSQL DB
  workflow-service/README.md
Labels: lgtm, approved

#211 CI: Rebase code with main branch when running the action
  .github/workflows/test.yml
  README.md
Labels: lgtm, approved

#218 refactor: reusing methods on workflow-definition service
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
Labels: lgtm, approved

#217 Refactor: small refactor on workflow-definition-service
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
Labels: lgtm, approved

#206 Fix: enable formatter for service SDK generated files
  workflow-service-sdk/pom.xml
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiCallback.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiClient.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiException.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiResponse.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/Configuration.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/GzipRequestInterceptor.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/JSON.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/LoginApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/Pair.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ProgressRequestBody.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ProgressResponseBody.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ProjectApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ServerConfiguration.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ServerVariable.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/StringUtil.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/WorkflowApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/WorkflowDefinitionApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/auth/ApiKeyAuth.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/auth/Authentication.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/auth/HttpBasicAuth.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/auth/HttpBearerAuth.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/ArgumentRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/ProjectRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/ProjectResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkDefinitionResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowCheckerTaskRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowDefinitionResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowOption.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowOptions.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowPropertiesDefinitionDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowStatusResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkStatusResponseDTO.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/LoginApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/ProjectApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/WorkflowApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/WorkflowDefinitionApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/ArgumentRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/ProjectRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/ProjectResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkDefinitionResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowCheckerTaskRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowDefinitionResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowOptionTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowOptionsTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowPropertiesDefinitionDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkFlowStatusResponseDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkStatusResponseDTOTest.java
Labels: lgtm, approved

#219 clean aspect
  workflow-engine/src/main/java/com/redhat/parodos/workflows/work/WorkStatus.java
  workflow-engine/src/main/java/com/redhat/parodos/workflows/workflow/ParallelFlowReport.java
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkFlowResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowResponseDTO.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/common/AbstractEntity.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/AssessmentInfrastructureWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/CheckerWorkFlowPostInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionInterceptor.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/WorkFlowExecution.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspectTest.java
Labels: lgtm, approved

#223 Fix OkHttp dependency issue
  pom.xml
Labels: lgtm, approved

#230 Fix tibco link
  external-dependencies/download-tibco.sh
Labels: lgtm, approved

#231 pom file cleanup
  notification-service-sdk/pom.xml
  notification-service/pom.xml
  parodos-model-api/pom.xml
  pattern-detection-library/pom.xml
  prebuilt-tasks/pom.xml
  workflow-engine/pom.xml
  workflow-examples/pom.xml
  workflow-service-sdk/pom.xml
  workflow-service/pom.xml
Labels: lgtm, approved

#205 Remove obsolete target from Makefile
  Makefile
Labels: lgtm, approved

#234 workflow-service-sdk version changes
  workflow-service-sdk/README.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiClient.java
Labels: lgtm, approved

#237 ci: Bump java to 17 in preparation to source/runtime migration
  .github/workflows/push.yml
  .github/workflows/test.yml
Labels: lgtm, approved

#239 Fix: make getHash test programmatic
  workflow-service/src/test/java/com/redhat/parodos/workflow/version/WorkFlowVersionServiceImplTest.java
Labels: lgtm, approved

#235 Migrate to Java 17
  Makefile
  docs/README.md
  external-dependencies/pom.xml
  notification-service/Dockerfile
  notification-service/pom.xml
  pom.xml
  workflow-service/Dockerfile
Labels: lgtm, approved

#242 add select parameter type
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Parameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterType.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterType.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/WorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/parameter/WorkFlowTaskParameter.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterTypeTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTypeTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/task/WorkFlowTaskTest.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/jira/JiraTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/notification/NotificationWorkFlowTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/MasterWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/checker/NamespaceApprovalWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/checker/SslCertificationApprovalWorkFlowCheckerTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/AdGroupsWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/LoadBalancerWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/NamespaceWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/OnboardingAssessmentTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SingleSignOnWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SplunkMonitoringWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SslCertificationWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/OcpOnboardingWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/ocponboarding/task/assessment/OnboardingOcpAssessmentTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/SecureAPIGetTestTask.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/custom/CustomWorkFlowConfiguration.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/master/checker/NamespaceApprovalWorkFlowCheckerTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/master/task/OnboardingAssessmentTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/escalation/JiraTicketApprovalEscalationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/AppLinkEmailNotificationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketCreationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/ocponboarding/task/JiraTicketEmailNotificationWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/SecureAPIGetTestTaskTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/converter/WorkFlowTaskParametersConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/converter/WorkParametersConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowRequestDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
Labels: lgtm, approved

#245 Workflow-service: fix dependecy
  workflow-service/pom.xml
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowPropertiesDefinitionDTO.java
Labels: lgtm, approved

#246 Remove workflow-service/.mvn
  pattern-detection-library/.mvn/wrapper/MavenWrapperDownloader.java
  pattern-detection-library/.mvn/wrapper/maven-wrapper.properties
  workflow-service/.mvn/wrapper/maven-wrapper.jar
  workflow-service/.mvn/wrapper/maven-wrapper.properties
Labels: lgtm, approved

#225 FLPATH-274 enable spring-cloud-config
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-local.yml
  notification-service/src/main/resources/application.yml
  workflow-service/pom.xml
  workflow-service/src/main/resources/application-dev.yml
  workflow-service/src/main/resources/application-local.yml
  workflow-service/src/main/resources/application.yml
Labels: lgtm, approved

#251 RestAPIWorkFlowTask: Use more reliable URL for the example
  workflow-examples/run_examples.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/SimpleWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTaskTest.java
Labels: lgtm, approved

#252 ci: to fix the push action use git-describe always
  workflow-examples/pom.xml
Labels: lgtm, approved

#254 Fix: format RestUtils and ExampleUtils
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/SimpleWorkFlow.java
Labels: lgtm, approved

#255 entity: Use Enum WorkflowProcessingType instead of String
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/dto/WorkDefinitionResponseDTOTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceDataTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
Labels: lgtm, approved

#244 Manifests: Openshift integration
  hack/manifests/base/deployment.yaml
  hack/manifests/openshift/ingress.yaml
  hack/manifests/openshift/kustomization.yaml
  hack/manifests/openshift/oauth.yaml
  hack/manifests/openshift/parodos-patch.yaml
Labels: lgtm, approved

#241 Rewrite escalation flow
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/ComplexWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/EscalationFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/utils/ExamplesUtils.java
Labels: lgtm, approved

#258 Update SDK changes after openapi.json was updated
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkDefinitionResponseDTO.md
  workflow-service-sdk/docs/WorkFlowDefinitionResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkDefinitionResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowDefinitionResponseDTO.java
Labels: lgtm, approved

#260 ci: Fail early if the git repo is dirty post build+test
  .github/workflows/test.yml
  .gitignore
  notification-service-sdk/.openapi-generator/FILES
Labels: lgtm, approved

#261 Fix Workflow examples integration tests
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/ComplexWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/PrebuiltWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/SimpleWorkFlow.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/UseSDKExample.java
Labels: lgtm, approved

#262 Fix format
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/PrebuiltWorkFlow.java
Labels: lgtm, approved

#263 fix Workflow level parameter select
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterType.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTypeTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/complex/ComplexWorkFlowConfiguration.java
Labels: lgtm, approved

#264 Version bump
  coverage/pom.xml
  notification-service-sdk/README.md
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiClient.java
  notification-service/README.md
  pom.xml
  workflow-service-sdk/README.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/invoker/ApiClient.java
  workflow-service/src/main/resources/application.yml
Labels: lgtm, approved

#265 down grade java version from 17 to 11
  .github/workflows/push.yml
  .github/workflows/test.yml
  Makefile
  notification-service/Dockerfile
  notification-service/pom.xml
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterType.java
  pom.xml
  workflow-service/Dockerfile
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegateTest.java
Labels: lgtm, approved

#266 Authentication: No Authentication when using oauth-proxy
  notification-service/src/main/java/com/redhat/parodos/notification/config/SecurityProperties.java
  notification-service/src/main/java/com/redhat/parodos/notification/security/SecurityConfiguration.java
  notification-service/src/main/resources/application.yml
  workflow-service/src/main/java/com/redhat/parodos/config/properties/SecurityProperties.java
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityConfiguration.java
  workflow-service/src/main/resources/application.yml
Labels: lgtm, approved

#270 FLPATH-330: Get the latest workflow execution status in project
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/ProjectResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/ProjectResponseDTO.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/project/dto/ProjectResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/project/service/ProjectServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepository.java
  workflow-service/src/test/java/com/redhat/parodos/project/service/ProjectServiceImplTest.java
Labels: lgtm, approved, jira/valid-reference

#271 Add tests for WorkFlowRepositoryTest
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepositoryTest.java
Labels: lgtm, approved

#275 Remove unneeded profile for tests
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepositoryTest.java
Labels: lgtm, approved

#276 dynamic parameter
  notification-service-sdk/.openapi-generator/FILES
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/annotation/Parameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterValueProvider.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterValueRequest.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkParameterValueResponse.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/WorkFlowTask.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkParameterTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/complex/ComplexWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/complex/parameter/ComplexWorkParameterValueProvider.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/complex/task/OnboardingAssessmentTask.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/complex/parameter/ComplexWorkParameterValueProviderTest.java
  workflow-service-sdk/README.md
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkParameterValueRequestDTO.md
  workflow-service-sdk/docs/WorkParameterValueResponseDTO.md
  workflow-service-sdk/docs/WorkflowDefinitionApi.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/WorkflowDefinitionApi.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkParameterValueRequestDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkParameterValueResponseDTO.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/WorkflowDefinitionApiTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkParameterValueRequestDTOTest.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkParameterValueResponseDTOTest.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkParameterValueRequestDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkParameterValueResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/parameter/WorkParameterService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/parameter/WorkParameterServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/parameter/WorkParameterServiceImplTest.java
Labels: lgtm, approved

#277 Manifest: use the right image on deployments
  hack/manifests/base/deployment.yaml
Labels: lgtm, approved

#280 Fix: remove from git `notification-service-sdk/.openapi-generator/FILES`
  notification-service-sdk/.openapi-generator/FILES
Labels: lgtm, approved

#268 Add Pull Request template
  .github/pull_request_template.md
Labels: lgtm, approved

#278 CI: move to quay parodos-dev org
  .github/workflows/push.yml
  Makefile
Labels: lgtm, approved

#282 Fix: use the correct backstage image
  hack/manifests/backstage/backstage.yaml
  hack/manifests/base/deployment.yaml
  hack/manifests/testing/kustomization.yaml
Labels: lgtm, approved

#285 Actions: fix checkout without the right info
  .github/workflows/test.yml
Labels: lgtm, approved

#284 fix: backstage app-config update
  hack/manifests/backstage/app-config.yaml
Labels: lgtm, approved

#283 NO-ISSUE: Make target to automate releases
  Makefile
Labels: lgtm, approved, jira/valid-reference

#287 CI: fix issues with images tags
  hack/manifests/testing/kustomization.yaml
Labels: lgtm, approved

#288 NO-ISSUE: Version bump
  coverage/pom.xml
  notification-service-sdk/README.md
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiClient.java
  notification-service/README.md
  pom.xml
  workflow-service-sdk/README.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/invoker/ApiClient.java
  workflow-service/src/main/resources/application.yml
Labels: lgtm, approved, jira/valid-reference
