Repository parodos-dev/parodos, pull requests merged in 2023-03, with the labels that each got.

#82 AuthN: based all authentication on LDAP.
  hack/manifests/base/deployment.yaml
  hack/manifests/testing/kustomization.yaml
  hack/manifests/testing/ldap.yaml
  hack/manifests/testing/test-server.ldif
  workflow-examples/run_examples.sh
  workflow-service/pom.xml
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
  workflow-service/src/main/java/com/redhat/parodos/config/properties/LdapConnectionProperties.java
  workflow-service/src/main/java/com/redhat/parodos/security/LocalSecurityConfiguration.java
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityConfiguration.java
  workflow-service/src/main/resources/application-dev.yml
  workflow-service/src/main/resources/application-local.yml
  workflow-service/src/main/resources/test-server.ldif
Labels: lgtm

#88 Nits and typos
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/context/WorkContextDelegate.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/parameter/WorkFlowTaskParameterType.java
  workflow-examples/pom.xml
  workflow-examples/run_examples.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/continued/complex/ComplexWorkFlowConfiguration.java
Labels: lgtm

#86 Workflow-service: add project controller tests
  workflow-service/src/main/java/com/redhat/parodos/project/controller/ProjectController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionController.java
  workflow-service/src/test/java/com/redhat/parodos/ControllerMockClient.java
  workflow-service/src/test/java/com/redhat/parodos/project/controller/ProjectControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionControllerTest.java
Labels: lgtm

#89 Draft: Feature/flpath 153 execution (not ready)
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/context/WorkContextDelegate.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/enums/WorkFlowStatus.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/enums/WorkFlowTaskStatus.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/MasterWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/AdGroupsWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/LoadBalancerWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/NamespaceWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SingleSignOnWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SplunkMonitoringWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/task/SslCertificationWorkFlowTask.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/WorkFlowDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowCheckerMappingDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowTaskDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/repository/WorkFlowCheckerMappingDefinitionRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/repository/WorkFlowWorkUnitRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowRequestDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/WorkFlowExecution.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/WorkFlowExecutionContext.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/converter/WorkContextConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/scheduler/WorkFlowSchedulerServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/util/WorkFlowDTOUtil.java
  workflow-service/src/main/resources/db/changelog/tables.xml
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm

#94 Extract getBase64Creds to a shared module
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/utils/CredUtils.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/utils/CredUtilsTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/SecureAPIGetTestTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/utils/RestUtils.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/SecureAPIGetTestTaskTest.java
  workflow-service/src/test/java/com/redhat/parodos/ControllerMockClient.java
Labels: lgtm

#97 fix workflow name
  workflow-examples/src/main/java/com/redhat/parodos/examples/continued/complex/ComplexWorkFlowConfiguration.java
Labels: lgtm, approved

#96 CI: Push images on each main push
  .github/workflows/push.yml
  Makefile
  hack/manifests/base/deployment.yaml
  hack/manifests/testing/ingress.yaml
  hack/manifests/testing/kustomization.yaml
Labels: lgtm

#98 Use Eager fetch type for checker workflow
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowCheckerDefinition.java
Labels: lgtm

#99 CI: Fix workflow-example
  workflow-examples/run_examples.sh
Labels: lgtm, approved

#93 Version bump
  coverage/pom.xml
  pom.xml
Labels: lgtm

#87 run_examples script: Fix run_simple_flow example
  workflow-examples/run_examples.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/RestAPIWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/SimpleWorkFlowConfiguration.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/RestAPIWorkFlowTaskTest.java
Labels: lgtm

#101 fix tests
  workflow-examples/run_examples.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/complex/ComplexWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTask.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/WorkFlowDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/continuation/WorkFlowContinuationServiceImplTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm

#100 WorkFlowExecutionAspect: Avoid NullPointerException on execution failure
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
Labels: lgtm

#92 Enforce java version in Makefile
  Makefile
Labels: lgtm

#103 Depencencies updates
  parodos-model-api/pom.xml
  pattern-detection-library/.flattened-pom.xml
  pattern-detection-library/pom.xml
  workflow-examples/pom.xml
  workflow-service/pom.xml
Labels: lgtm

#105 Remove redundant dependency
  workflow-service/pom.xml
Labels: lgtm

#102 CI: Test run all workflow examples
  .github/workflows/test.yml
  workflow-examples/run_examples.sh
Labels: lgtm

#106 Update jar version
  workflow-examples/start_workflow_service.sh
  workflow-service/start_workflow_service.sh
Labels: lgtm

#107 Add 'provided' scope to existing jars in examples
  workflow-examples/pom.xml
Labels: lgtm, approved

#104 Fix example parameters names
  workflow-examples/run_examples.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTask.java
Labels: lgtm, approved

#90 Tools: add a way to install sample backstage in plain kubernetes
  hack/manifests/backstage/Readme.md
  hack/manifests/backstage/app-config.yaml
  hack/manifests/backstage/backstage.yaml
  hack/manifests/backstage/kustomization.yaml
  hack/manifests/backstage/namespace.yaml
  hack/manifests/backstage/parodos-patch.yaml
  hack/manifests/backstage/postgres.yaml
  hack/manifests/base/deployment.yaml
Labels: lgtm, approved

#111 Add make target to run locally
  Makefile
Labels: lgtm

#109 workflow parameters
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/context/WorkContextDelegate.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/BaseWorkFlowTask.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/WorkFlowDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspect.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/WorkFlowDelegateTest.java
Labels: lgtm

#114 Version bump
  coverage/pom.xml
  notification-service/.flattened-pom.xml
  pattern-detection-library/.flattened-pom.xml
  pom.xml
  workflow-examples/start_workflow_service.sh
  workflow-service/start_workflow_service.sh
Labels: lgtm

#108 Workflow-service increasing test coverage
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/controller/WorkFlowControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm

#115 CI: collect kind logs on integration testing
  .github/workflows/test.yml
  hack/manifests/testing/kustomization.yaml
  hack/manifests/testing/parodos-patch.yaml
Labels: lgtm, approved

#122 Version bump
  coverage/pom.xml
  notification-service/.flattened-pom.xml
  pattern-detection-library/.flattened-pom.xml
  pom.xml
  workflow-examples/start_workflow_service.sh
  workflow-service/start_workflow_service.sh
Labels: lgtm

#120 Manifest: Add health and livenessProbe in containers
  hack/manifests/base/deployment.yaml
Labels: lgtm

#125 Remove unused annotation
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
Labels: lgtm, approved

#128 Move OWNERS file to root directory
  OWNERS
Labels: lgtm, approved

#136 CI: Adjust a bit the readinessProbe
  hack/manifests/base/deployment.yaml
Labels: lgtm

#135 Upload workflow-examples jar to artifacts
  .github/workflows/test.yml
Labels: lgtm, approved

#129 Decouple examples from service
  Makefile
  docker-compose/docker-compose.yml
  workflow-examples/pom.xml
  workflow-examples/start_workflow_service.sh
  workflow-service/Dockerfile
  workflow-service/pom.xml
  workflow-service/start_workflow_service.sh
Labels: lgtm, approved

#141 avoid null pointer exception when subWorkflow not executed
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm, approved

#138 add workflow status rest endpoint
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowWorkDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/controller/WorkFlowController.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkFlowStatusResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkStatusResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/repository/WorkFlowRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowExecutionAspectTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/controller/WorkFlowControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm, approved

#140 CI: remove a redundant mvn compile on push
  .github/workflows/push.yml
Labels: lgtm, approved

#142 Workflow-service: Fix migrations issues on integration test
  workflow-service/src/main/resources/db/changelog/data.xml
  workflow-service/src/main/resources/db/changelog/tables.xml
Labels: lgtm, approved

#132 Workflow-service: Parameters as jsonschema
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkFlowParameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterType.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/WorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/parameter/WorkFlowTaskParameter.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/parameter/WorkFlowTaskParameterType.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/parameter/WorkFlowParameterTypeTest.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/task/parameter/WorkFlowTaskParameterTypeTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTask.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTaskTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/WorkFlowDefinitionResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/dto/converter/WorkFlowTaskDefinitionDTOConverter.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/controller/WorkFlowDefinitionControllerTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
Labels: lgtm

#137 component scan from different packages
  workflow-examples/src/main/java/org/parodos/workflow/examples/CustomWorkFlowConfiguration.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/task/CustomWorkFlowTask.java
  workflow-service/README.md
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
  workflow-service/src/main/resources/application.yml
Labels: approved

#145 Change formatting behavior
  .github/workflows/push.yml
  pom.xml
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
Labels: lgtm, approved

#123 Add a workflow task that sends a message to topic in TIBCO
  external-dependencies/download-tibco.sh
  external-dependencies/pom.xml
  pom.xml
  prebuilt-tasks/pom.xml
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/Tibjms.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibjmsImpl.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTaskTest.java
  workflow-examples/README.md
  workflow-examples/pom.xml
  workflow-examples/run_tibco.sh
  workflow-examples/src/main/java/com/redhat/parodos/examples/TibcoWorkFlowConfiguration.java
Labels: lgtm, approved

#146 FLPATH-204: cleanup definitions in db before loading new beans
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowWorkDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceDataTest.java
Labels: lgtm, approved

#158 fix checker logic
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
Labels: approved

#161 Version bump
  coverage/pom.xml
  notification-service/.flattened-pom.xml
  pattern-detection-library/.flattened-pom.xml
  pom.xml
  workflow-examples/start_workflow_service.sh
  workflow-service-sdk/README.md
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkDefinitionResponseDTO.md
  workflow-service-sdk/docs/WorkFlowDefinitionResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/ApiClient.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkDefinitionResponseDTO.java
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkFlowDefinitionResponseDTO.java
  workflow-service/generated/openapi/api-docs.json
  workflow-service/start_workflow_service.sh
Labels: lgtm, approved

#162 CI: Add logs when deployment timeout is hit
  .github/workflows/test.yml
Labels: lgtm, approved

#163 Change OpenAPI filename to `openapi.json`
  workflow-service-sdk/pom.xml
  workflow-service/generated/openapi/openapi.json
  workflow-service/pom.xml
Labels: lgtm, approved

#165 Add license and SCM info to service SDK pom
  workflow-service-sdk/pom.xml
Labels: lgtm, approved

#157 Flpath 183
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/consts/WorkFlowConstants.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/BaseWorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/WorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/checker/BaseWorkFlowCheckerTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/infrastructure/BaseInfrastructureWorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/version/GithubVersionManager.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/version/VersionManager.java
  parodos-model-api/src/test/java/com/redhat/parodos/workflow/task/WorkFlowTaskTest.java
  prebuilt-tasks/pom.xml
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibcoJmsServiceImpl.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibcoMessageService.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTask.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/Tibjms.java
  prebuilt-tasks/src/main/java/com/redhat/parodos/tasks/tibco/TibjmsImpl.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/tibco/TibcoJmsServiceImplTest.java
  prebuilt-tasks/src/test/java/com/redhat/parodos/tasks/tibco/TibcoWorkFlowTaskTest.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/TibcoWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/escalation/EscalationWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/master/MasterWorkFlowConfiguration.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTask.java
  workflow-examples/src/main/java/com/redhat/parodos/examples/simple/task/SecureAPIGetTestTask.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/base/BaseAssessmentTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/base/BaseInfrastructureWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/base/BaseWorkFlowCheckerTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/LoggingWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/RestAPIWorkFlowTaskTest.java
  workflow-examples/src/test/java/com/redhat/parodos/examples/simple/task/SecureAPIGetTestTaskTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/aspect/WorkFlowTaskExecutionAspect.java
Labels: approved

#155 Flpath 204: update database with new workflow configuration after app restarts
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/BaseWorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/WorkFlowTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/assessment/BaseAssessmentTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/checker/BaseWorkFlowCheckerTask.java
  parodos-model-api/src/main/java/com/redhat/parodos/workflow/task/infrastructure/BaseInfrastructureWorkFlowTask.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/CustomWorkFlowConfiguration.java
  workflow-examples/src/main/java/org/parodos/workflow/examples/task/SimpleWorkFlowCheckerTask.java
  workflow-service/src/main/java/com/redhat/parodos/WorkflowServiceApplication.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/WorkFlowDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowCheckerMappingDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowTaskDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/entity/WorkFlowWorkDefinition.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/repository/WorkFlowWorkRepository.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionService.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/entity/WorkFlowExecutionContext.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/util/WorkFlowDTOUtil.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceDataTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/definition/service/WorkFlowDefinitionServiceImplTest.java
Labels: approved

#166 bug: fix main branch build failure
  workflow-examples/src/main/java/org/parodos/workflow/examples/CustomWorkFlowConfiguration.java
Labels: bug, approved

#164 Check if generated files are up-to-date
  .github/workflows/push.yml
Labels: approved

#168 Refactor workflow and works status DTO build
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/WorkStatusResponseDTO.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/model/WorkStatusResponseDTO.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/model/WorkStatusResponseDTOTest.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/dto/WorkStatusResponseDTO.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegate.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceDelegateTest.java
  workflow-service/src/test/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImplTest.java
Labels: lgtm, approved

#173 Fix: notification-service ldap port
  notification-service/src/main/resources/application-local.yml
Labels: lgtm, approved

#150 Add start_notification_service.sh script
  workflow-examples/start_notification_service.sh
  workflow-examples/start_workflow_service.sh
Labels: lgtm, approved

#171 Update spring
  notification-service/.flattened-pom.xml
  notification-service/pom.xml
  parodos-model-api/pom.xml
  workflow-examples/pom.xml
  workflow-service/pom.xml
Labels: lgtm, approved

#153 Enable graceful shutdown endpoint
  workflow-examples/start_workflow_service.sh
  workflow-service/run_workflow_service.sh
  workflow-service/src/main/java/com/redhat/parodos/security/SecurityConfiguration.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/execution/service/WorkFlowServiceImpl.java
  workflow-service/src/main/java/com/redhat/parodos/workflow/registry/BeanWorkFlowRegistryImpl.java
  workflow-service/src/main/resources/application-dev.yml
  workflow-service/src/main/resources/application-local.yml
  workflow-service/src/main/resources/application.yml
  workflow-service/start_workflow_service.sh
Labels: lgtm, approved

#178 Added a dev user for testing, improved error logging
  notification-service/src/main/java/com/redhat/parodos/notification/service/impl/NotificationRecordServiceImpl.java
  notification-service/src/main/resources/test-server.ldif
Labels: lgtm, approved

#179 Fix: change workflow-service openapi generator phases
  workflow-service/pom.xml
Labels: lgtm, approved

#156 FLPATH-208: Add notification-service API auto generation
  notification-service-sdk/.gitignore
  notification-service-sdk/.openapi-generator-ignore
  notification-service-sdk/.openapi-generator/FILES
  notification-service-sdk/.openapi-generator/VERSION
  notification-service-sdk/.openapi-generator/openapi.json-generate-client-api-code.sha256
  notification-service-sdk/README.md
  notification-service-sdk/api/openapi.yaml
  notification-service-sdk/docs/Link.md
  notification-service-sdk/docs/NotificationMessageApi.md
  notification-service-sdk/docs/NotificationMessageCreateRequestDTO.md
  notification-service-sdk/docs/NotificationRecordApi.md
  notification-service-sdk/docs/NotificationRecordResponseDTO.md
  notification-service-sdk/docs/PageMetadata.md
  notification-service-sdk/docs/Pageable.md
  notification-service-sdk/docs/PagedModelNotificationRecordResponseDTO.md
  notification-service-sdk/pom.xml
  notification-service-sdk/src/main/AndroidManifest.xml
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiCallback.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiClient.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiException.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ApiResponse.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/Configuration.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/GzipRequestInterceptor.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/JSON.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/NotificationMessageApi.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/NotificationRecordApi.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/Pair.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ProgressRequestBody.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ProgressResponseBody.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ServerConfiguration.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/ServerVariable.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/StringUtil.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/auth/ApiKeyAuth.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/auth/Authentication.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/auth/HttpBasicAuth.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/api/auth/HttpBearerAuth.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/Link.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/NotificationMessageCreateRequestDTO.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/NotificationRecordResponseDTO.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/PageMetadata.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/Pageable.java
  notification-service-sdk/src/main/java/com/redhat/parodos/notification/sdk/model/PagedModelNotificationRecordResponseDTO.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/api/NotificationMessageApiTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/api/NotificationRecordApiTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/LinkTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/NotificationMessageCreateRequestDTOTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/NotificationRecordResponseDTOTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/PageMetadataTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/PageableTest.java
  notification-service-sdk/src/test/java/com/redhat/parodos/notification/sdk/model/PagedModelNotificationRecordResponseDTOTest.java
  notification-service/.flattened-pom.xml
  notification-service/generated/openapi.json
  notification-service/pom.xml
  notification-service/src/main/resources/application-dev.yml
  notification-service/src/main/resources/application-local.yml
  notification-service/src/main/resources/application.yml
  pom.xml
Labels: lgtm

#182 Fix: squash dupicated declaration of `maven-clean-plugin`
  notification-service/pom.xml
Labels: lgtm, approved

#185 Set scope for workflow-example dependencies
  workflow-examples/pom.xml
Labels: lgtm, approved

#186 Rewrite SDK example like `run_simple_flow` with SDK
  workflow-examples/src/test/java/com/redhat/parodos/examples/integration/UseSDKExample.java
Labels: lgtm, approved

#187 dummy login controller
  workflow-service-sdk/README.md
  workflow-service-sdk/api/openapi.yaml
  workflow-service-sdk/docs/LoginApi.md
  workflow-service-sdk/src/main/java/com/redhat/parodos/sdk/api/LoginApi.java
  workflow-service-sdk/src/test/java/com/redhat/parodos/sdk/api/LoginApiTest.java
  workflow-service/generated/openapi/openapi.json
  workflow-service/src/main/java/com/redhat/parodos/security/LoginController.java
Labels: lgtm, approved
